### ISSUE TITLE
Ask about your GCC installation

### ISSUE THREAD

**Issue by J8M** [n27051538/solaris_exporter#1]
When executing `pkg install pkg:/developer/gcc/gcc-c-5`

`Creating Plan (Solver setup): -
pkg install: No matching version of developer/gcc/gcc-c-5 can be installed:
  Reject:  pkg://solaris/developer/gcc/gcc-c-5@5.4.0-0.175.3.22.0.1.0
  Reason:  No version for 'require' dependency on library/mpc@0.9,5.11-0.175.3.0.0.30.0 can be found`

**Comment by n27051538** [comment]
Hello,
You need to setup offline repository first.

ср, 10 июня 2020 г., 6:36 小老弟 <notifications@github.com>:

**Comment by J8M** [comment]
Can I use your exporter on Solaris 11.3

**Comment by n27051538** [comment]
It is tested on on Solaris 11.3.25, 11.4.4, 10u11(limited) SPARC. Works fine.
