### ISSUE TITLE
pkgadd with proxy authentification...

### ISSUE THREAD

**Issue by mcarbonneaux** [n27051538/solaris_exporter#2]
`pkgadd` not support `user` and `password` in proxy environement variable http_proxy and https_proxy.

you must download `pkgutil`  package with wget/curl before.

```
# export http_proxy=http://<user>:<password>@proxy.example.com:3128  
# export https_proxy=https://<user>:<password>@proxy.example.com:3128  
# wget http://get.opencsw.org/now 
# pkgadd -d ./now
```

The last `pkgutil` work fine with this proxy variable syntax, you can do csw pkg install with it.

**Comment by n27051538** [comment]
Thank you. I reflect your experience in documentation and comments.
