### ISSUE TITLE
On solaris 10 username/groupname max length are lower than the size of the user created for smf install !

### ISSUE THREAD

**Issue by mcarbonneaux** [n27051538/solaris_exporter#3]
The username and groupname `prometheus` used in install script are too long on solaris 10 to install the exporter as SMF service.

To make installation work, i'm oblige to rename username and groupname to max 8 characters name in `solaris_exporter_smf.sh` and `solaris_exporter_role.sh`.

**Comment by n27051538** [comment]
Thank you.
I use this exporter with different user with short login. I renamed user for pushing to github, but seems that I need to rename him again.

**Comment by mcarbonneaux** [comment]
For information i'm testing it on solaris sparc.
