### ISSUE TITLE
Unfortunately does not work in Solaris 11.4.35

### ISSUE THREAD

**Issue by rastus123** [n27051538/solaris_exporter#6]
I had such high hopes..
Unfortunately needs a touch up to get up to date I expect.. Certainly python 2.7 is an issue at least...

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.

I will have a dig around, but unlikely to get it sorted myself unfortunately

**Comment by n27051538** [comment]
Hello,
You may use pip 20.3 or less. Also use psutil version 5.7.0.
Those versions support python 2.7.
Python 2.7 is the only version installed on my old Solaris hosts. Max Solaris version on my hosts is 11.4.4 and seems that it will be never upgraded. All newer applications now are work on Linux.
But if you want you could update solaris_exporter for Python 3.x support.

**Comment by n27051538** [comment]
Hello,
I made an update of solaris_exporter.py in the new branch for support of Python 3, https://github.com/n27051538/solaris_exporter/blob/forPython3/solaris_exporter.py , it is in testing.
I still have troubles with installation of psutil for Python 3.5 in Solaris 11.4.4, and opened ticket about it https://github.com/giampaolo/psutil/issues/2065.

**Comment by n27051538** [comment]
Please test new version [v2022Feb05](https://github.com/n27051538/solaris_exporter/blob/forPython3/solaris_exporter.py), I placed it into separate branch [forPython3](https://github.com/n27051538/solaris_exporter/tree/forPython3).

**Comment by n27051538** [comment]
Fixed in release [v2022Feb05](https://github.com/n27051538/solaris_exporter/releases/tag/v2022Feb05)
